name: director
listen: "{{HOST|default('0.0.0.0')}}:{{PORT|default(8080)}}"
env: "{{ENV}}"
redis_dsn: "{{REDIS_DSN|default('redis://redis:6379')}}"
ch_dsn: "{{CHP_DSN|default('http://default:default@host:9090')}}"
data_dir: "{{DATA_DIR|default('/data')}}"
# initial
default_services: ['mmgeo', 'sxgeo', 'uaparser']

images:
  # - name: rst/band-base-py
  #   path: "{{BASE_IMG_PATH|default(IMAGES_PATH+'/band_base_py')}}"
  - prefix: rst/band-
    collection: true
    base: rockstat/band-base-py
    path: "{{IMAGES_PATH}}/band_set"
  - prefix: rst/user-
    collection: true
    base: rockstat/band-base-py
    path: "{{IMAGES_PATH}}/user"
  - prefix: rst/rockme-
    collection: true
    path: "{{IMAGES_PATH}}/rockme_set"

# following params will be paseed to image and container builder functions
container_params:
  network: "{{NETWORK|default('custom')}}"
  memory: 367001600 # limit 350mb
  bind_ip: "{{BIND_HOST_IP}}"
  env:
    HOST: '0.0.0.0'
    REDIS_DSN: "{{REDIS_DSN|default('redis://redis:6379')}}"
    CHP_DSN: "{{CHP_DSN|default('')}}"
    CH_DSN: "{{CH_DSN|default('')}}"
    CHS_DSN: "{{CHS_DSN|default('')}}"
    JSON_LOGS: JSON_LOGS={{JSON_LOGS|default(1)}}
  etc_hosts:
    host: "{{HOST_ADDR|default('172.17.0.1')}}"
  